import { Injectable } from '@nestjs/common';
import { Role, StudyStatus } from '@prisma/client';
import * as ExcelJS from 'exceljs';
import type { TDocumentDefinitions } from 'pdfmake/interfaces';
import { PrismaService } from '../../infra/prisma/prisma.service';

// pdfmake's server printer + bundled Roboto (Vietnamese-capable) fonts.
// Loaded via require to avoid CJS/ESM default-export typing friction.
/* eslint-disable @typescript-eslint/no-require-imports */
const PdfPrinter = require('pdfmake') as new (fonts: unknown) => {
  createPdfKitDocument: (doc: TDocumentDefinitions) => NodeJS.ReadableStream & { end: () => void };
};
const vfs = require('pdfmake/build/vfs_fonts') as Record<string, string>;
/* eslint-enable @typescript-eslint/no-require-imports */
const pdfFonts = {
  Roboto: {
    normal: Buffer.from(vfs['Roboto-Regular.ttf'], 'base64'),
    bold: Buffer.from(vfs['Roboto-Medium.ttf'], 'base64'),
    italics: Buffer.from(vfs['Roboto-Italic.ttf'], 'base64'),
    bolditalics: Buffer.from(vfs['Roboto-MediumItalic.ttf'], 'base64'),
  },
};

export type Lang = 'vi' | 'en';
export type ReportType = 'tuition' | 'scores' | 'students' | 'classes';

export interface ReportColumn {
  header: string;
  key: string;
  width?: number;
}
export interface ReportTable {
  title: string;
  subtitle: string;
  columns: ReportColumn[];
  rows: Record<string, string | number>[];
}

export interface ReportQuery {
  classId?: string;
  status?: string;
  from?: string;
  to?: string;
}

// ---- i18n dictionaries (backend has no i18n runtime) ----
const TITLES: Record<Lang, Record<ReportType, string>> = {
  vi: {
    tuition: 'Báo cáo học phí',
    scores: 'Báo cáo điểm học viên',
    students: 'Danh sách học viên',
    classes: 'Báo cáo lớp học',
  },
  en: {
    tuition: 'Tuition Report',
    scores: 'Student Scores Report',
    students: 'Student List',
    classes: 'Class Report',
  },
};

const COLS: Record<Lang, Record<ReportType, Record<string, string>>> = {
  vi: {
    tuition: {
      student: 'Học viên',
      email: 'Email',
      class: 'Lớp',
      total: 'Tổng học phí',
      paid: 'Đã đóng',
      remaining: 'Còn lại',
      paymentCount: 'Số đợt đã đóng',
      status: 'Trạng thái',
      dueDate: 'Hạn đóng',
    },
    scores: {
      date: 'Ngày',
      class: 'Lớp',
      student: 'Học viên',
      type: 'Loại',
      note: 'Ghi chú',
      value: 'Điểm',
      max: 'Tối đa',
      teacher: 'Người nhập',
    },
    students: {
      code: 'ID',
      name: 'Họ tên',
      phone: 'SĐT',
      email: 'Email',
      level: 'Trình độ',
      classes: 'Lớp học',
      status: 'Trạng thái',
      joined: 'Ngày tham gia',
    },
    classes: {
      class: 'Lớp',
      level: 'Trình độ',
      teacher: 'Giáo viên',
      students: 'Sĩ số',
      total: 'Tổng buổi',
      completed: 'Đã học',
      remaining: 'Còn lại',
    },
  },
  en: {
    tuition: {
      student: 'Student',
      email: 'Email',
      class: 'Class',
      total: 'Total',
      paid: 'Paid',
      remaining: 'Remaining',
      paymentCount: 'Payments',
      status: 'Status',
      dueDate: 'Due Date',
    },
    scores: {
      date: 'Date',
      class: 'Class',
      student: 'Student',
      type: 'Type',
      note: 'Note',
      value: 'Score',
      max: 'Max',
      teacher: 'Recorded by',
    },
    students: {
      code: 'ID',
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      level: 'Level',
      classes: 'Classes',
      status: 'Status',
      joined: 'Joined',
    },
    classes: {
      class: 'Class',
      level: 'Level',
      teacher: 'Teacher',
      students: 'Students',
      total: 'Total Sessions',
      completed: 'Completed',
      remaining: 'Remaining',
    },
  },
};

const UI: Record<Lang, { period: string; allTime: string; generated: string; rows: string }> = {
  vi: {
    period: 'Khoảng thời gian',
    allTime: 'Toàn bộ thời gian',
    generated: 'Xuất ngày',
    rows: 'dòng',
  },
  en: { period: 'Period', allTime: 'All time', generated: 'Generated', rows: 'rows' },
};

const FOOTER = 'Generated by Schedule Teacher LMS';

@Injectable()
export class ReportService {
  constructor(private readonly prisma: PrismaService) {}

  private dateRange(q: ReportQuery): { gte?: Date; lte?: Date } | undefined {
    if (!q.from && !q.to) return undefined;
    return {
      ...(q.from ? { gte: new Date(q.from) } : {}),
      ...(q.to ? { lte: new Date(q.to) } : {}),
    };
  }

  private subtitle(lang: Lang, q: ReportQuery, count: number): string {
    const ui = UI[lang];
    const period = q.from || q.to ? `${ui.period}: ${q.from || '…'} – ${q.to || '…'}` : ui.allTime;
    return `${period} · ${ui.generated} ${new Date().toISOString().slice(0, 10)} · ${count} ${ui.rows}`;
  }

  private cols(lang: Lang, type: ReportType, defs: [string, number][]): ReportColumn[] {
    return defs.map(([key, width]) => ({ key, width, header: COLS[lang][type][key] ?? key }));
  }

  // ---- Dispatch ----
  async build(
    teacherId: string,
    type: ReportType,
    q: ReportQuery,
    lang: Lang,
  ): Promise<ReportTable> {
    switch (type) {
      case 'tuition':
        return this.tuitionData(teacherId, q, lang);
      case 'scores':
        return this.scoresData(teacherId, q, lang);
      case 'students':
        return this.studentListData(teacherId, q, lang);
      case 'classes':
        return this.classData(teacherId, q, lang);
    }
  }

  // ---- Data builders ----
  private async tuitionData(teacherId: string, q: ReportQuery, lang: Lang): Promise<ReportTable> {
    const range = this.dateRange(q);
    const tuitions = await this.prisma.tuition.findMany({
      where: {
        teacherId,
        ...(q.classId ? { classId: q.classId } : {}),
        ...(range ? { createdAt: range } : {}),
      },
      include: {
        student: { select: { fullName: true, email: true } },
        class: { select: { name: true } },
        _count: { select: { payments: true } },
      },
      orderBy: { createdAt: 'desc' },
    });
    const rows = tuitions.map((t) => {
      const total = Number(t.totalAmount);
      const paid = Number(t.paidAmount);
      return {
        student: t.student.fullName,
        email: t.student.email,
        class: t.class.name,
        total,
        paid,
        remaining: total - paid,
        paymentCount: t._count.payments,
        status: t.status,
        dueDate: t.dueDate ? t.dueDate.toISOString().slice(0, 10) : '',
      };
    });
    return {
      title: TITLES[lang].tuition,
      subtitle: this.subtitle(lang, q, rows.length),
      columns: this.cols(lang, 'tuition', [
        ['student', 26],
        ['email', 26],
        ['class', 20],
        ['total', 14],
        ['paid', 14],
        ['remaining', 14],
        ['paymentCount', 12],
        ['status', 16],
        ['dueDate', 14],
      ]),
      rows,
    };
  }

  private async scoresData(teacherId: string, q: ReportQuery, lang: Lang): Promise<ReportTable> {
    const range = this.dateRange(q);
    const scores = await this.prisma.score.findMany({
      where: {
        teacherId,
        ...(q.classId ? { classId: q.classId } : {}),
        ...(range ? { scoredAt: range } : {}),
      },
      include: {
        student: { select: { fullName: true } },
        class: { select: { name: true } },
      },
      orderBy: [{ scoredAt: 'desc' }],
    });

    // Resolve who recorded each score (createdBy → name; future-proof for assistants).
    const creatorIds = [
      ...new Set(scores.map((s) => s.createdBy).filter((id): id is string => !!id)),
    ];
    const creators = creatorIds.length
      ? await this.prisma.user.findMany({
          where: { id: { in: creatorIds } },
          select: { id: true, fullName: true },
        })
      : [];
    const nameById = new Map(creators.map((u) => [u.id, u.fullName]));

    const rows = scores.map((s) => ({
      date: s.scoredAt.toISOString().slice(0, 10),
      class: s.class.name,
      student: s.student.fullName,
      type: s.type,
      note: s.label ?? '',
      value: Number(s.value),
      max: Number(s.maxValue),
      teacher: s.createdBy ? (nameById.get(s.createdBy) ?? '—') : '—',
    }));
    return {
      title: TITLES[lang].scores,
      subtitle: this.subtitle(lang, q, rows.length),
      columns: this.cols(lang, 'scores', [
        ['date', 14],
        ['class', 20],
        ['student', 24],
        ['type', 12],
        ['note', 18],
        ['value', 10],
        ['max', 10],
        ['teacher', 20],
      ]),
      rows,
    };
  }

  private async studentListData(
    teacherId: string,
    q: ReportQuery,
    lang: Lang,
  ): Promise<ReportTable> {
    const range = this.dateRange(q);
    const students = await this.prisma.user.findMany({
      where: {
        teacherId,
        role: Role.STUDENT,
        deletedAt: null,
        ...(q.status ? { studentProfile: { studyStatus: q.status as StudyStatus } } : {}),
        ...(q.classId ? { enrollments: { some: { classId: q.classId } } } : {}),
        ...(range ? { createdAt: range } : {}),
      },
      select: {
        fullName: true,
        email: true,
        phone: true,
        createdAt: true,
        studentProfile: { select: { code: true, studyStatus: true } },
        enrollments: {
          where: { class: { deletedAt: null } },
          select: { class: { select: { name: true, level: true } } },
        },
      },
      orderBy: { createdAt: 'desc' },
    });
    const rows = students.map((s) => ({
      code: s.studentProfile?.code ?? '',
      name: s.fullName,
      phone: s.phone ?? '',
      email: s.email,
      level: s.enrollments.map((e) => e.class.level).find(Boolean) ?? '',
      classes: s.enrollments.map((e) => e.class.name).join(', '),
      status: s.studentProfile?.studyStatus ?? 'STUDYING',
      joined: s.createdAt.toISOString().slice(0, 10),
    }));
    return {
      title: TITLES[lang].students,
      subtitle: this.subtitle(lang, q, rows.length),
      columns: this.cols(lang, 'students', [
        ['code', 12],
        ['name', 24],
        ['phone', 16],
        ['email', 26],
        ['level', 12],
        ['classes', 24],
        ['status', 14],
        ['joined', 14],
      ]),
      rows,
    };
  }

  private async classData(teacherId: string, q: ReportQuery, lang: Lang): Promise<ReportTable> {
    const range = this.dateRange(q);
    const classes = await this.prisma.class.findMany({
      where: { teacherId, deletedAt: null, ...(range ? { createdAt: range } : {}) },
      select: {
        id: true,
        name: true,
        level: true,
        totalSessions: true,
        teacher: { select: { fullName: true } },
        _count: {
          select: {
            enrollments: true,
            sessions: { where: { status: { not: 'CANCELLED' }, deletedAt: null } },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    const ids = classes.map((c) => c.id);
    const completedGroups = ids.length
      ? await this.prisma.teachingSession.groupBy({
          by: ['classId'],
          where: { classId: { in: ids }, status: 'COMPLETED', deletedAt: null },
          _count: { _all: true },
        })
      : [];
    const completedById = new Map(completedGroups.map((g) => [g.classId, g._count._all]));

    const rows = classes.map((c) => {
      const total = c.totalSessions ?? c._count.sessions;
      const completed = completedById.get(c.id) ?? 0;
      return {
        class: c.name,
        level: c.level ?? '',
        teacher: c.teacher.fullName,
        students: c._count.enrollments,
        total,
        completed,
        remaining: Math.max(0, total - completed),
      };
    });
    return {
      title: TITLES[lang].classes,
      subtitle: this.subtitle(lang, q, rows.length),
      columns: this.cols(lang, 'classes', [
        ['class', 22],
        ['level', 12],
        ['teacher', 22],
        ['students', 12],
        ['total', 14],
        ['completed', 12],
        ['remaining', 12],
      ]),
      rows,
    };
  }

  // ---- Renderers ----
  async toExcel(table: ReportTable): Promise<Buffer> {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet(table.title.slice(0, 31));
    ws.columns = table.columns.map((c) => ({ header: c.header, key: c.key, width: c.width ?? 18 }));
    ws.getRow(1).font = { bold: true };
    for (const row of table.rows) ws.addRow(row);
    const data = await wb.xlsx.writeBuffer();
    return Buffer.from(data);
  }

  async toPdf(table: ReportTable): Promise<Buffer> {
    const printer = new PdfPrinter(pdfFonts);
    const header = table.columns.map((c) => ({
      text: c.header,
      bold: true,
      fontSize: 9,
      color: '#ffffff',
      fillColor: '#5D87FF',
      margin: [0, 2, 0, 2] as [number, number, number, number],
    }));
    const body = table.rows.map((r) =>
      table.columns.map((c) => ({
        text: String(r[c.key] ?? ''),
        fontSize: 9,
        margin: [0, 1, 0, 1] as [number, number, number, number],
      })),
    );

    const doc: TDocumentDefinitions = {
      pageOrientation: 'landscape',
      pageSize: 'A4',
      pageMargins: [28, 56, 28, 44],
      defaultStyle: { font: 'Roboto', fontSize: 9 },
      header: {
        text: table.title,
        alignment: 'center',
        bold: true,
        fontSize: 16,
        margin: [0, 18, 0, 0],
      },
      content: [
        {
          text: table.subtitle,
          alignment: 'center',
          fontSize: 9,
          color: '#888',
          margin: [0, 0, 0, 12],
        },
        {
          table: {
            headerRows: 1,
            widths: table.columns.map(() => '*'),
            body: [header, ...body],
          },
          layout: {
            fillColor: (rowIndex: number) =>
              rowIndex > 0 && rowIndex % 2 === 0 ? '#f6f8fc' : null,
            hLineWidth: () => 0.5,
            vLineWidth: () => 0,
            hLineColor: () => '#e0e0e0',
          },
        },
      ],
      footer: (currentPage: number, pageCount: number) => ({
        margin: [28, 14, 28, 0],
        columns: [
          { text: FOOTER, alignment: 'left', fontSize: 8, color: '#aaaaaa' },
          {
            text: `${currentPage}/${pageCount}`,
            alignment: 'right',
            fontSize: 8,
            color: '#aaaaaa',
          },
        ],
      }),
    };

    const pdfDoc = printer.createPdfKitDocument(doc);
    return new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];
      pdfDoc.on('data', (c: Buffer) => chunks.push(c));
      pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
      pdfDoc.on('error', reject);
      pdfDoc.end();
    });
  }
}
